Revisado 00-intro.md
Eloquent-JavaScript-Espanol/Eloquent-JavaScript-ES pull request #3
Opened 2020-10-21 20:21 UTC by a-morelos

Revisé el texto y realice pequeños ajustes de redacción y ortografía

2020-10-23 22:36 UTC, hectorip requested changes
Hice algunas observaciones.

2020-10-23 22:36 UTC, hectorip commented on 00_intro.md
> -tardarían _para siempre_ a mano. Es una forma de hacer que tu herramienta
Te parece si lo cambiamos por: "...cosas que manualmente nunca teminarías." ?

2020-10-23 22:36 UTC, hectorip commented on 00_intro.md
> +capacidades. Estás bien —sólo tienes que seguir intentando.
Lo cambiamos por una coma?

2020-10-23 22:36 UTC, hectorip commented on 00_intro.md
> +separadas tienden a estar involucradas—, y para hacer que todo funcione,
Igual, los cambiamos por comas?

2020-10-24 03:17 UTC, a-morelos reviewed
Deje algunas anotaciones sobre dudas que tenía

2020-10-24 03:17 UTC, a-morelos commented on 00_intro.md
> -tardarían _para siempre_ a mano. Es una forma de hacer que tu herramienta
No me convence del todo, pero me dio una idea. ¿Qué tal si queda de la siguiente manera?:

«Te permite hacer en segundos cosas que tardarían siglos a mano.»

2020-10-24 03:17 UTC, a-morelos commented on 00_intro.md
> +capacidades. Estás bien —sólo tienes que seguir intentando.
Me parece bien

2020-10-24 03:17 UTC, a-morelos commented on 00_intro.md
> +separadas tienden a estar involucradas—, y para hacer que todo funcione,
En este caso decidí usar los guiones conforme a las reglas de puntuación. Dejo la [referencia correspondiente](https://www.rae.es/dpd/raya)

2020-10-24 03:17 UTC, a-morelos commented on 00_intro.md
> +nada, y crece fácilmente bajo el tecleado de nuestras manos.
Aquí he pensado en cambiarlo por «el tecleo de nuestras manos» ó «el teclear de nuestras manos».

2020-10-24 03:21 UTC, a-morelos reviewed
Cambio de signo de puntuación

2020-10-24 04:31 UTC, hectorip commented on 00_intro.md
> -tardarían _para siempre_ a mano. Es una forma de hacer que tu herramienta
Me gusta.

2020-10-24 04:31 UTC, hectorip commented on 00_intro.md
> +separadas tienden a estar involucradas—, y para hacer que todo funcione,
De acuerdo, también me gusta.

2020-10-24 04:32 UTC, merged